---
title: "TCSAM2013 Model Results"
author: "William Stockhausen"
date: "August 01, 2016"
output: word_document
params: 
    paths: none
    numRecent: 15
    plot1stObs: TRUE
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo=FALSE, error=FALSE, message=FALSE, warning=FALSE,
                      dpi=300,fig.width=6.5,out.width="6.5in")
```

```{r init}
    require(ggplot2);
    require(ggthemes);
    require(reshape2);
    require(rTCSAM2013);
    paths<-params$paths;
    numRecent<-params$numRecent;
    plot1stObs<-as.logical(params$plot1stObs);
```

#Input model cases
```{r getFiles,results='asis'}
    if (!is.list(paths)){
        cat("'paths' parameter is not a list!\n")
    }
    obj<-list();
    for (case in names(paths)){
        cat(case,": ",paths[[case]],"\n",sep='')
        obj[[case]]<-getResLst(inp.dir=paths[[case]])
    }
    figno<-1;
```

#Parameter estimates
```{r plots.Parameters,results='asis'}
    plots<-compareModelResults.Params(obj,
                                      showPlot=FALSE);
    figno<-(printGGList(plots,figno=figno,show=TRUE))$figno;
```

#Surveys
```{r plots.Surveys,results='asis'}
    plots<-compareModelResults.SurveyQuantities(obj,
                                                numRecent=numRecent,
                                                plot1stObs=plot1stObs);
    figno<-(printGGList(plots,figno=figno,show=TRUE))$figno;
```

